### ISSUE TITLE
Traduire le site en anglais

### ISSUE THREAD

**Issue by GruberAdam** [BFL-CPNV/ProjetWeDB-Furnitures#6]
Anglais ou français

**Comment by BFL-CPNV** [comment]
Anglais ?

De : GruberAdam <notifications@github.com>
Envoyé : mercredi, 23 septembre 2020 08:56
À : BFL-CPNV/ProjetWeDB-Furnitures <ProjetWeDB-Furnitures@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : [BFL-CPNV/ProjetWeDB-Furnitures] Choisir la langue du site (#6)


Anglais ou français

**Comment by BFL-CPNV** [comment]
Anglais, décidé par le groupe
